sources:
  india:
    - https://feeds.bbci.co.uk/news/world/asia/india/rss.xml
    - https://www.thehindu.com/news/national/feeder/default.rss
    - https://timesofindia.indiatimes.com/rssfeedstopstories.cms
    - https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml
    - https://www.hindustantimes.com/feeds/rss/latest/rssfeed.xml
  world:
    - https://feeds.bbci.co.uk/news/world/rss.xml
    - https://rss.dw.com/xml/rss-en-world
    - https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml
    - https://www.hindustantimes.com/feeds/rss/geopolitics/rssfeed.xml
  business:
    - https://feeds.bbci.co.uk/news/business/rss.xml
    - https://www.thehindu.com/business/feeder/default.rss
    - https://timesofindia.indiatimes.com/rssfeedstopstories.cms
  technology:
    - https://feeds.bbci.co.uk/news/technology/rss.xml
    - https://www.thehindu.com/sci-tech/technology/feeder/default.rss
    - https://techcrunch.com/feed/
  science:
    - https://feeds.bbci.co.uk/news/science_and_environment/rss.xml
  defence:
    - https://feeds.bbci.co.uk/news/world/rss.xml
    - https://www.thehindu.com/news/national/feeder/default.rss

limits:
  max_articles_per_source: 35
  max_total_articles: 700
  max_related_articles: 5
